---

- name: Create container configuration
  docker_container_configurator:
    templates: "{{ templates }}"
    config: "{{ config }}"
    run_order: "{{ run_order | default(omit) }}"

- name: "Manage containers"
  docker:
    cap_add: "{{ item.cap_add | default(omit) }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    command: "{{ item.command | default(omit) }}"
    count: "{{ item.count | default(omit) }}"
    cpu_set : "{{ item.cpu_set  | default(omit) }}"
    cpu_shares: "{{ item.cpu_shares | default(omit) }}"
    detach: "{{ item.detach | default(omit) }}"
    devices: "{{ item.devices | default(omit) }}"
    dns: "{{ item.dns | default(omit) }}"
    docker_api_version: "{{ item.docker_api_version | default(omit) }}"
    docker_url: "{{ item.docker_url | default(omit) }}"
    docker_user: "{{ item.docker_user | default(omit) }}"
    domainname: "{{ item.domainname | default(omit) }}"
    email: "{{ item.email | default(omit) }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    expose: "{{ item.expose | default(omit) }}"
    extra_hosts: "{{ item.extra_hosts | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    image: "{{ item.image | default(omit) }}"
    insecure_registry: "{{ item.insecure_registry | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    links: "{{ item.links | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    log_opt: "{{ item.log_opt | default(omit) }}"
    lxc_conf: "{{ item.lxc_conf | default(omit) }}"
    memory_limit: "{{ item.memory_limit | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    net: "{{ item.net | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    pid: "{{ item.pid | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    privileged: "{{ item.privileged | default(omit) }}"
    publish_all_ports: "{{ item.publish_all_ports | default(omit) }}"
    pull: "{{ item.pull | default(omit) }}"
    read_only: "{{ item.read_only | default(omit) }}"
    registry: "{{ item.registry | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    restart_policy_retry: "{{ item.restart_policy_retry | default(omit) }}"
    signal: "{{ item.signal | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    stdin_open: "{{ item.stdin_open | default(omit) }}"
    stop_timeout: "{{ item.stop_timeout | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    tls_ca_cert: "{{ item.tls_ca_cert | default(omit) }}"
    tls_client_cert: "{{ item.tls_client_cert | default(omit) }}"
    tls_client_key: "{{ item.tls_client_key | default(omit) }}"
    tls_hostname: "{{ item.tls_hostname | default(omit) }}"
    tty: "{{ item.tty | default(omit) }}"
    ulimits: "{{ item.ulimits | default(omit) }}"
    use_tls: "{{ item.use_tls | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    volumes_from: "{{ item.volumes_from | default(omit) }}"
  with_list: "{{ docker_container_configurations }}"
